# Copyright 2024 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

seed: 2022

# number of samples in training data to randomly subsample if greater than 0
sub_samples: 0

ca_data_path: /home/ma/a/al3615/data/california_house_price/train.pq
ca_indices_folder: /home/ma/a/al3615/projects/text_and_tabular/california_house_experiments/indices

dataset_name: ca
task: finetune # pretrain or finetune
num_classes: 1
perf_metric: RMSE
supervised_loss: mse_loss

# modalities presence
image: false
text: true
time: false
tab: true

mm_encoder_trainable: true
loading_from_finetuned: true # This should be true if finetune_intialize_from is pointing to a finetuned model
finetune_initialize_from: /home/ma/a/al3615/projects/lanistr/lanistr/output_dir/ca_housing/ca_housing_pretrain_resnet/finetune_chkpoint_best.pth # random, pretrain or path to checkpoint
# NOTE: Swap on pretrain/finetune to freeze for finetuning
text_encoder_trainable: true
text_proj_trainable: true
tabular_encoder_trainable: true
tabular_proj_trainable: true

output_dir: ./output_dir/ca_housing
experiment_name: ca_housing_pretrain_resnet_test_transfer_learning

test_ratio: 0.1

# If running with tabnet the batch size must be larger than 2*ngpus_per_node*2 as virtual batch size is set to 1/2 of the batch size
# and batchnorm needs >=2 samples to compute the mean and variance
# If finetuning with a lot of freezing - we will be storing less gradients so can increase batch size
# For pretraining - works with 16 on 2 GPUS
# For finetuning - works with 256 on 2 GPUS
train_batch_size: 16
eval_batch_size: 16
test_batch_size: 16

scheduler:
  num_epochs: 500
  warmup_epochs: 5

optimizer:
  learning_rate: 0.00001
  weight_decay: 0.02
  clip_value: 5.0

mm_hidden_dim: 2048
mm_output_dim: 2048
mm_emmbedding_dim: 768  # this is the embedding size of lanistr

# simsiam pretraining projector and predictor
projection_type: SimSiam
predictor_hidden_dim: 512
predictor_out_dim: 2048

# unimodal encoders projection dim
projection_dim: 768

classifier_hidden_dim: 768

text_encoder_name: bert-base-uncased
max_token_length: 512
text_embedding_dim: 768

mlm_probability: 0.15

# tabular encoder
tabular_encoder_name: resnet

tabnet:
  pretraining_ratio: 0.15
  cat_emb_dim: 3
  mask_type: sparsemax
  n_d: 64
  n_a: 64
  output_dim: 1 # This is a pointless parameter that original creators left in - presumably to test TabNet? Not used by LANISTR

resnet:
  pretraining_ratio: 0.15
  hidden_dim: 256
  num_layers: 3
  dropout: 0.1
  activation: relu
  cat_emb_dim: 3 # TODO: Replace this with target mean encoding at some point

# data parallelism
multiprocessing_distributed: false
dist_backend: nccl
ngpus_per_node: 2
world_size: 1
nodes: 1
workers: 20

training:
  early_stopping:
    patience: 5
    min_delta: 0.001
    mode: min

# Pretraining loss weights
lambda_mim: 1.0
lambda_mlm: 1.0
lambda_mtm: 0.1
lambda_mmm: 1.0
lambda_mfm: 0.01

pretrain_resume: false # If true - prior checkpoint must exist
pretrain_initialize_from_epoch: 0