# Copyright 2024 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

seed: 2022

# number of samples in training data to randomly subsample if greater than 0
sub_samples: 0

do_train: true
do_test: false

dataset_name: mimic-iv
task: finetune
num_classes: 2
perf_metric: auroc

# modalities presense
image: true
text: true
time: true
tab: false

finetune_initialize_from: pretrain
timeseries_encoder_trainable: false
text_encoder_trainable: false
image_encoder_trainable: false
tabular_encoder_trainable: false
mm_encoder_trainable: true
text_proj_trainable: true
image_proj_trainable: true
timeseries_proj_trainable:  true

# image modality
image_size: 224
image_crop: 224
mask_patch_size: 16
model_patch_size: 16
image_masking_ratio: 0.5

root_data_dir: ./data/MIMIC-IV-V2.2/physionet.org/files
image_data_dir: ./data/MIMIC-IV-V2.2/physionet.org/files/mimic-cxr-jpg/2.0.0
task_data_dir: ./data/MIMIC-IV-V2.2/in-hospital-mortality
unimodal_data_dir: ./data/MIMIC-IV-V2.2/in-hospital-mortality/unimodal_data
preprocessed_data_dir: ./data/MIMIC-IV-V2.2/
# do not change normalizer_file and discretizer_config_path
normalizer_file: ./data/MIMIC-IV-V2.2/normalizer.csv
discretizer_config_path: ./data/MIMIC-IV-V2.2/discretizer_config.json

output_dir: ./data/output_dir/mimic_pretrain
experiment_name: mimic_finetune

test_ratio: 0.1

train_batch_size: 512
eval_batch_size: 617
test_batch_size: 617

scheduler:
  num_epochs: 500
  warmup_epochs: 5

optimizer:
  learning_rate: 0.0001
  weight_decay: 0.02
  clip_value: 5.0

mm_hidden_dim: 2048
mm_output_dim: 2048
mm_emmbedding_dim: 768  # this is the embedding size of lanistr

# simsiam pretraining projector and predictor
projection_type: SimSiam
predictor_hidden_dim: 512
predictor_out_dim: 2048

# unimodal encoders projection dim
projection_dim: 768

classifier_hidden_dim: 768

text_encoder_name: bert-base-uncased
max_token_length: 512
text_embedding_dim: 768

mlm_probability: 0.15

image_encoder_name: google/vit-base-patch16-224
image_embedding_dim: 768


timeseries_input_dim: 76
timeseries_dim_feedforward: 256
timeseries_max_seq_len: 48
timeseries_layers: 3
timeseries_n_heads: 4
timeseries_dropout: 0.1
timeseries_embedding_dim: 76
timeseries_activation: gelu
timeseries_masking_ratio: 0.15
timeseries_mean_mask_length: 3
timeseries_mask_mode: separate
timeseries_mask_distribution: geometric
impute_strategy: zero
start_time: zero
timestep: 1.0

# data parallelism
multiprocessing_distributed: true
dist_backend: nccl
ngpus_per_node: 8
world_size: 1
workers: 16
