seed: 2022
sub_samples: 0
ca_data_path: /home/ma/a/al3615/data/california_house_price/train.pq
ca_indices_folder: /home/ma/a/al3615/projects/text_and_tabular/california_house_experiments/indices
dataset_name: ca
task: pretrain
num_classes: 1
perf_metric: RMSE
supervised_loss: mse_loss
image: false
text: true
time: false
tab: true
finetune_initialize_from: random
text_encoder_trainable: false
mm_encoder_trainable: true
text_proj_trainable: true
output_dir: ./output_dir/ca_housing/ca_housing_pretrain
experiment_name: ca_housing_pretrain
test_ratio: 0.1
train_batch_size: 128
eval_batch_size: 64
test_batch_size: 64
scheduler:
  num_epochs: 500
  warmup_epochs: 5
optimizer:
  learning_rate: 0.0001
  weight_decay: 0.02
  clip_value: 5.0
mm_hidden_dim: 2048
mm_output_dim: 2048
mm_emmbedding_dim: 768
projection_type: SimSiam
predictor_hidden_dim: 512
predictor_out_dim: 2048
projection_dim: 768
classifier_hidden_dim: 768
text_encoder_name: bert-base-uncased
max_token_length: 512
text_embedding_dim: 768
mlm_probability: 0.15
tabular_encoder_name: tabnet
tabular_encoder_trainable: true
tabular_proj_trainable: true
tabular_output_dim: 768
tabular_embedding_dim: 64
tabular_pretraining_ratio: 0.15
tabular_cat_emb_dim: 3
tabular_mask_type: sparsemax
tabular_n_d: 64
tabular_n_a: 64
multiprocessing_distributed: false
dist_backend: nccl
ngpus_per_node: 2
world_size: 1
nodes: 1
workers: 20
lambda_mim: 1.0
lambda_mlm: 1.0
lambda_mtm: 0.1
lambda_mmm: 1.0
lambda_mfm: 0.01
pretrain_resume: true
pretrain_initialize_from_epoch: 0
split: 0
local_rank: 0
eval_on: test
distributed: false
device: 0
